fix: replace ProtobufWkt with Protobuf for envoy-1.36 compatibility
In envoy-1.36, the namespace alias changed from ProtobufWkt to Protobuf.
Update filter_manager.cc to use the correct namespace.

Error:
  source/common/http/filter_manager.cc:499:15: error: use of undeclared
  identifier 'ProtobufWkt'; did you mean 'Protobuf'?

Fixed:
  ProtobufWkt::Struct -> Protobuf::Struct

Change-Id: Ib087e16001c82b298be2f63821d96bb20caf54b7
Co-developed-by: Cursor <noreply@cursor.com>